version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: cafeteria-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cafeteria_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serviço do Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cafeteria-backend
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: cafeteria_db
      DB_PORT: 5432
      API_KEY: cafescript-chave-secreta-98765

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cafeteria-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data: